import Link from 'next/link';
import { Sidebar } from '@/components/sidebar';
import { IntegrationsClient } from '@/components/integrations-client';
import { env } from '@/lib/env';
export const dynamic='force-dynamic';
export default function IntegrationsPage(){const endpoint=`${env.appUrl()}/mcp`;return <main className="shell"><Sidebar/><section className="content">
  <header className="topbar"><div><b>AI туслахтай холбох</b><span>ChatGPT · Claude · Монгол контент</span></div><Link className="pill" href="/studio">Студи рүү</Link></header>
  <section className="mcpHero"><div className="eyebrow">RAVS × ТАНЫ AI ТУСЛАХ</div><h1>Санаанаас бүтээл хүртэл.<br/><em>Монгол хэлээр.</em></h1><p>ChatGPT эсвэл Claude-д RAVS-ийг холбоод загвараа сонгох, storyboard, prompt, caption бэлтгэх, кредитээ шалгах, зөвшөөрсөн бүтээлээ үүсгэх боломжтой.</p><div className="mcpLabels"><span>Хэрэглэгч бүрийн OAuth зөвшөөрөл</span><span>Кредитийн дээд хязгаар</span><span>Эрхээ хүссэн үедээ цуцална</span></div></section>
  <IntegrationsClient endpoint={endpoint}/>
  <section className="mcpSetupGrid"><article><span className="eyebrow">01 · CLAUDE</span><h2>Claude-д нэмэх</h2><ol><li>Claude-ийн Customize → Connectors хэсэгт ор.</li><li>+ Add → Add custom connector сонгоод нэрийг <b>RAVS</b>, remote MCP URL-ийг дээрх холбоосоор оруул.</li><li>Continue дар. Authentication-д Sign in now, OAuth client-д <b>Register automatically</b> сонго. Дараа нь RAVS бүртгэлээр нэвтрэн эрхээ зөвшөөр.</li><li>Шинэ чатад RAVS холболтыг идэвхжүүлээд Монгол хэлээр даалгавраа өг.</li></ol><p>Байгууллагын workspace-д эзэмшигч эсвэл администратор эхэлж холболт нэмэх шаардлагатай байж болно.</p></article>
  <article><span className="eyebrow">02 · CHATGPT</span><h2>ChatGPT-д нэмэх</h2><ol><li>Веб хувилбарт өөрийн эрхээр Developer mode / custom MCP app боломж нээлттэй эсэхийг шалга.</li><li>Settings → Apps → Create хэсэгт RAVS нэр, MCP холбоосыг оруулж OAuth сонго.</li><li>RAVS бүртгэлээр нэвтэрч эрхээ зөвшөөрөөд хэрэгслүүдийг шалган аппыг үүсгэ.</li><li>Чатдаа RAVS аппыг сонгоод хийх контентоо Монгол хэлээр тайлбарла.</li></ol><p>Үүсгэх, цуцлах зэрэг бичих үйлдлийн дэмжлэг нь төлөвлөгөө, workspace-ийн тохиргооноос хамаарна. Холболт нэмэх товч харагдахгүй бол администраторын эрх эсвэл өөр төлөвлөгөө хэрэгтэй байж болно.</p></article></section>
  <section className="mcpWorkflow"><h2>Бүтэн контент бэлтгэх дараалал</h2><div className="mcpSteps">{[['Санаа ба загвар','Зорилго, үзэгч, сувгаа хэл. Туслах тохирох загварын заавар, боломжит хэмжээг шалгана.'],['Storyboard ба бичвэр','Кадр бүрийн үйлдэл, камер, prompt, Монгол caption, hook, CTA болон хуваарь бэлтгэнэ.'],['Тооцоо ба зөвшөөрөл','Кредит, тохиргоогоо харж үүсгэхийг зөвшөөр. Унших эрхтэй холболт төлбөртэй хүсэлт эхлүүлэхгүй.'],['Үүсгэлт ба үр дүн','Төлөвийг шалгаж, дууссан файлтай үед холбоос авна. Олон хэсгийн эвлүүлэг, нийтлэх ажлаа тусад нь гүйцэтгэнэ.']].map(([title,text],i)=><article key={title}><span>{String(i+1).padStart(2,'0')}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
  <section className="mcpPrompt"><h2>Эхлэх даалгаврын жишээ</h2><blockquote>“Монгол кофе брэндэд Instagram Reels-ийн 3 санаа гарга. Үзэгчид 20–35 насныхан. Сонгосон санаанд storyboard, кадр бүрийн prompt, Монгол caption, hook, CTA бэлд. RAVS-ээс загварын заавар, 9:16 хэмжээ, кредитийг шалга. Миний зөвшөөрөл авсны дараа л видео үүсгэ.”</blockquote><p>RAVS нь зураг, видео үүсгэлтийг гүйцэтгэнэ. Бичвэрийг таны AI туслах боловсруулна. Автоматаар эвлүүлсэн, сошиалд нийтэлсэн гэж мэдэгдэхгүй.</p></section>
  <section className="mcpTools"><h2>Холболтоор ашиглах хэрэгслүүд</h2><div className="mcpToolTable"><table><thead><tr><th>Хэрэгсэл</th><th>Үүрэг</th><th>Эрх</th></tr></thead><tbody>{[['ravs_list_models','Загвар, зориулалт, хугацаа, хэмжээг харьцуулах','Унших'],['ravs_model_guide','Тухайн хувилбарын заавар, тохиргоо','Унших'],['ravs_content_brief','Монгол кампанит ажлын чиглэл, бичвэрийн бүтэц','Унших'],['ravs_estimate','Оролт шалгах, кредит тооцоолох','Унших'],['ravs_account','Өөрийн кредит','Унших'],['ravs_list_generations','Өөрийн сүүлийн бүтээлүүд','Унших'],['ravs_generation_status','Төлөв шалгах, бэлэн файлын холбоос авах','Унших'],['ravs_create_generation','Зөвшөөрсөн дээд кредиттэй зураг/видео үүсгэх','Үүсгэх'],['ravs_cancel_generation','Эхэлж амжаагүй хүсэлт цуцлах','Үүсгэх']].map(row=><tr key={row[0]}>{row.map((c,i)=><td key={i}>{i===0?<code>{c}</code>:c}</td>)}</tr>)}</tbody></table></div><p>Scope тохируулах сонголт байгаа бол бүтээл үүсгэхэд <code>ravs:read ravs:generate offline_access</code>, зөвхөн уншихад <code>ravs:read</code> хэрэглэ. Зөвшөөрлийн хуудсан дээр үүсгэх эрх харагдахгүй бол тухайн холболт үүсгэлт эхлүүлэхгүй.</p><p>Higgsfield түлхүүр сервер дээр хадгалагдана. ChatGPT, Claude-д түлхүүрээ оруулах шаардлагагүй.</p></section>
</section></main>}
