"use client";
import {useEffect,useState} from 'react';
type Demo={id:string;title:string;videoUrl:string;published:boolean;category:string};
export function AdminDemos(){
 const [items,setItems]=useState<Demo[]>([]),[source,setSource]=useState(''),[urls,setUrls]=useState<string[]>([]),[title,setTitle]=useState(''),[category,setCategory]=useState('effects'),[direct,setDirect]=useState(''),[busy,setBusy]=useState(''),[message,setMessage]=useState('');
 async function load(){const r=await fetch('/api/admin/demos',{cache:'no-store'});if(!r.ok)throw new Error('Видео сан ачаалж чадсангүй.');const d=await r.json();setItems(d.items||[]);}
 useEffect(()=>{load().catch(e=>setMessage(e.message));},[]);
 async function act(body:Record<string,unknown>){setBusy(String(body.action));setMessage('');try{const r=await fetch('/api/admin/demos',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,sourceUrl:source,category})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Алдаа гарлаа.');if(body.action==='discover'){setUrls(d.videos||[]);setMessage(d.videos?.length?`${d.videos.length} видео олдлоо. Урьдчилан үзээд импортлоно уу.`:'Хуудаснаас нийтийн видео олдсонгүй. Шууд CDN MP4 холбоос оруулж болно.');}else{setMessage(d.duplicate?'Энэ видео өмнө импортлогдсон.':'Хадгаллаа. Сайт дээр шууд шинэчлэгдэнэ.');await load();}}catch(e){setMessage(e instanceof Error?e.message:'Алдаа гарлаа.');}finally{setBusy('');}}
 const officialSuggestions=[
  {name:"Viral Presets",url:"https://higgsfield.ai/effects",category:"effects"},
  {name:"Шинэ Template-ууд",url:"https://higgsfield.ai/apps/trending-templates",category:"effects"},
  {name:"Video Editing",url:"https://higgsfield.ai/apps/video-editing",category:"effects"},
  {name:"Cinema Motion",url:"https://higgsfield.ai/apps/camera-motion",category:"genjutsu"},
  {name:"Product Ads",url:"https://higgsfield.ai/apps/ads-products",category:"marketing"},
  {name:"AI Influencer",url:"https://higgsfield.ai/ai-influencer-studio",category:"influencer"},
 ];
 return <section className="adminGuide"><h2>Demo видео импорт</h2><p>Higgsfield-ийн албан эх сурвалжийн шинэ жишээ бичлэгийг шалгаж, тоглуулан зөвшөөрөлтэйгээр сонгож нэмнэ. Албан сайтын бүх контент шууд импортлох эрхтэй гэсэн үг биш. Нийтлэх зөвшөөрөлгүй видеог бүү хуул.</p>
 <div className="adminDemoSuggestions" aria-label="Higgsfield албан эх сурвалжууд"><b>Шинэ жишээ шалгах эх сурвалж</b><div style={{display:"flex",gap:8,flexWrap:"wrap",margin:"12px 0 18px"}}>{officialSuggestions.map(item=><button type="button" key={item.name} className="ghost" onClick={()=>{setSource(item.url);setCategory(item.category);setUrls([]);}}>{item.name} ↗</button>)}</div></div><label>Higgsfield хуудасны холбоос<input className="wide" aria-label="Higgsfield хуудасны холбоос" value={source} onChange={e=>setSource(e.target.value)} placeholder="https://higgsfield.ai/..."/></label><button className="ghost" disabled={!!busy||!source} onClick={()=>act({action:'discover'})}>Шинэ бичлэгүүдийг шалгах</button><p><label>Бичлэгийн нэр<input aria-label="Бичлэгийн нэр" value={title} onChange={e=>setTitle(e.target.value)} maxLength={160}/></label> <label>Ангилал<select value={category} onChange={e=>setCategory(e.target.value)}><option value="effects">Эффект</option><option value="genjutsu">Genjutsu</option><option value="marketing">Маркетинг</option><option value="influencer">AI дүр</option><option value="cinema">Кино</option></select></label></p><label>Шууд CDN видео холбоос<input className="wide" aria-label="Шууд CDN видео холбоос" value={direct} onChange={e=>setDirect(e.target.value)} placeholder="https://cdn.higgsfield.ai/...mp4"/></label><button className="primary" disabled={!!busy||!source||!direct||!title} onClick={()=>act({action:'import',videoUrl:direct,title})}>Татаж импортлох</button>{message&&<p role="status">{message}</p>}{busy&&<p role="status">{busy==='import'?'Видео татаж хадгалж байна…':'Шалгаж байна…'}</p>}
 <div className="guideSteps">{urls.map((u,i)=><div key={u}><video controls playsInline preload="none" src={u} style={{width:'100%'}}/><button className="primary" disabled={!!busy||!title} onClick={()=>act({action:'import',videoUrl:u,title:urls.length>1?`${title} · ${i+1}`:title})}>Энэ бичлэгийг импортлох</button></div>)}</div>
 <h3>Импортлосон сан · {items.length}</h3><div className="guideSteps">{items.map(v=><div key={v.id}><video controls playsInline preload="none" src={v.videoUrl} style={{width:'100%'}}/><b>{v.title}</b><p>{v.published?'Нийтлэгдсэн':'Нуугдсан'} · {v.category}</p><button className="ghost" disabled={!!busy} onClick={()=>act({action:'publish',id:v.id,published:!v.published})}>{v.published?'Нуух':'Нийтлэх'}</button></div>)}</div><p>Нийтийн MP4/WebM · 30MB хүртэл. Хуудасны бүтэц өөрчлөгдвөл шууд видео холбоос ашиглана. Дараагийн шинэчлэлт бүрийг “Шинэ бичлэгүүдийг шалгах” товчоор шалгана.</p></section>;
}
