"use client";
import { useEffect,useState } from 'react';
type Row={id:string;modelSlug:string;prompt:string;input:unknown;createdAt:string;costCredits:number;userId:string};
export function AdminReconciliation(){
 const [rows,setRows]=useState<Row[]>([]),[ids,setIds]=useState<Record<string,string>>({}),[confirmed,setConfirmed]=useState<Record<string,boolean>>({}),[rejected,setRejected]=useState<Record<string,boolean>>({}),[error,setError]=useState(''),[busy,setBusy]=useState(''),[loaded,setLoaded]=useState(false);
 async function load(){try{const r=await fetch('/api/admin/generations/reconcile',{cache:'no-store'});if(!r.ok)throw new Error();setRows((await r.json()).generations);setLoaded(true);}catch{setError('Сэргээх хүсэлтүүдийг авч чадсангүй.');}}
 useEffect(()=>{void load()},[]);
 async function restore(row:Row,notAccepted=false){setBusy(row.id);setError('');try{const r=await fetch('/api/admin/generations/reconcile',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({generationId:row.id,providerRequestId:ids[row.id],confirmMatch:confirmed[row.id],confirmNotAccepted:notAccepted&&rejected[row.id]})});const d=await r.json();if(!r.ok)throw new Error(d.error);await load();}catch(e){setError(e instanceof Error?e.message:'Сэргээж чадсангүй.');}finally{setBusy('');}}
 return <section className="adminGuide"><h2>Тодорхойгүй илгээлтийг сэргээх</h2><p>Сүлжээ тасарсан үед үүсгэлт хүлээн авагдсан эсэхийг батлах боломжгүй тул автоматаар давтан илгээхгүй, кредит буцаахгүй. Higgsfield Console дээр загвар, оролт, цагийг тулгаж хүсэлтийн ID-г олно. Доорх үйлдэл шинэ үүсгэлт эхлүүлэхгүй.</p>{error&&<p role="alert" className="formError">{error}</p>}{!loaded?<p>Шалгаж байна…</p>:rows.length===0?<p>Сэргээх шаардлагатай хүсэлт алга.</p>:rows.map(row=><div key={row.id} className="mcpReconcileRow"><strong>{row.modelSlug} · {row.costCredits} кредит</strong><p>RAVS ID: <code>{row.id}</code><br/>Хэрэглэгч: <code>{row.userId}</code> · {new Date(row.createdAt).toLocaleString('mn-MN')}</p><details><summary>Эх оролттой тулгах</summary><pre>{JSON.stringify(row.input,null,2)}</pre></details><label>Higgsfield Console-ийн request ID<input value={ids[row.id]||''} onChange={e=>setIds({...ids,[row.id]:e.target.value})} maxLength={128}/></label><label><input type="checkbox" checked={!!confirmed[row.id]} onChange={e=>setConfirmed({...confirmed,[row.id]:e.target.checked})}/> Энэ хүсэлтийн загвар, оролт, цаг Console-ийн хүсэлттэй таарсныг шалгасан.</label><button className="primary" disabled={!!busy||!confirmed[row.id]||!ids[row.id]} onClick={()=>restore(row)}>{busy===row.id?'Сэргээж байна…':'Одоо байгаа хүсэлттэй холбох'}</button><details><summary>Provider хүлээн аваагүй хүсэлтийг хаах</summary><label><input type="checkbox" checked={!!rejected[row.id]} onChange={e=>setRejected({...rejected,[row.id]:e.target.checked})}/> Console болон provider мэдээллээр энэ хүсэлт хүлээн авагдаагүй, төлбөртэй ажил эхлээгүйг баталгаажуулсан.</label><button className="pill" disabled={!!busy||!rejected[row.id]} onClick={()=>restore(row,true)}>Үүсгэлт эхлээгүйг баталгаажуулж кредит буцаах</button></details></div>)}</section>;
}
