import Link from 'next/link';
import { ArrowRight, BookOpen, Check, ExternalLink, Lightbulb, MonitorPlay, Ratio, Timer } from 'lucide-react';
import type { RavsModel } from '@/lib/models';
import { aspectLabel, durationLabel, modelGuide, optionLabel, parameterHelp, parameterLabel, resolutionLabel } from '@/lib/model-guides';

export function ModelGuide({model,compact=false}:{model:RavsModel;compact?:boolean}){
 const guide=modelGuide(model);
 return <section className={'mnModelGuide '+(compact?'compactGuide':'')} aria-label={model.name+' Монгол заавар'}>
  <div className="guideIntro"><div><span className="eyebrow"><BookOpen size={14}/> МОНГОЛ ГАРЫН АВЛАГА</span><h2>{guide.mode}</h2><p>{guide.purpose}</p></div><span className={'schemaState '+(model.apiVerified?'documented':'pending')}>{model.apiVerified?'Параметр баталгаажсан':'Баримт нягталж байна'}</span></div>
  <div className="guideSpecCards"><div><MonitorPlay size={19}/><small>НЯГТАРШИЛ</small><b>{resolutionLabel(model)}</b></div><div><Ratio size={19}/><small>КАДРЫН ХАРЬЦАА</small><b>{aspectLabel(model)}</b></div><div><Timer size={19}/><small>ҮРГЭЛЖЛЭХ ХУГАЦАА</small><b>{durationLabel(model)}</b></div></div>
  {model.apiVerified&&<p className="guideRequired"><Check size={14}/>{guide.required.length?'Заавал оруулах: '+guide.required.join(', '):'Заавал гэсэн талбаргүй. Бүтээлийн тайлбар эсвэл жишиг материалаа оруул.'}</p>}
  <details open={!compact} className="guideWalkthrough"><summary>Алхамчилсан заавар, зөвлөгөө</summary><ol>{guide.steps.map((step,i)=><li key={step}><span>{String(i+1).padStart(2,'0')}</span><p>{step}</p></li>)}</ol><div className="guideTips"><b><Lightbulb size={16}/> Илүү сайн үр дүнд хүрэх</b>{guide.tips.map(tip=><p key={tip}>{tip}</p>)}</div><div className="guidePrompt"><small>ЖИШЭЭ ТАЙЛБАР · ӨӨРИЙН САНААНД ТААРУУЛ</small>{guide.promptTranslation&&<p>{guide.promptTranslation}</p>}{guide.promptTranslation&&<small>АНГЛИ ХУВИЛБАР · ЗАГВАРТ ИЛГЭЭХ ЖИШЭЭ</small>}<p>{guide.prompt}</p>{!compact&&model.apiVerified&&<Link className="primary" href={'/studio?model='+model.slug+'&prompt='+encodeURIComponent(guide.prompt)}>Энэ тайлбараар эхлэх <ArrowRight size={14}/></Link>}</div></details>
  {!compact&&!!model.parameters?.length&&<section className="parameterReference"><h2>Тохиргоо бүрийн тайлбар</h2><div className="parameterTableWrap"><table><thead><tr><th>Тохиргоо</th><th>Сонголт / хязгаар</th><th>Үндсэн утга</th></tr></thead><tbody>{model.parameters.map(f=><tr key={f.name}><td><b>{parameterLabel(f.name)}{f.required&&<span className="requiredPill">Заавал</span>}</b><p>{parameterHelp(f)}</p></td><td>{f.options?.map(optionLabel).join(' · ')||[f.minimum!==undefined?'Доод: '+f.minimum:undefined,f.maximum!==undefined?'Дээд: '+f.maximum:undefined,f.minLength!==undefined?'Текст ≥ '+f.minLength:undefined,f.maxLength!==undefined?'Текст ≤ '+f.maxLength:undefined].filter(Boolean).join(' · ')||'Албан зааврын бүтэцтэй утга'}</td><td>{f.default===undefined?'—':typeof f.default==='boolean'?(f.default?'Асаалттай':'Унтраалттай'):typeof f.default==='string'?optionLabel(f.default):JSON.stringify(f.default)}</td></tr>)}</tbody></table></div></section>}
  <div className="guideSourceLine"><span>Албан параметр ба RAVS-ийн практик зөвлөгөө · 2026.10.06</span>{guide.source&&<a href={guide.source} target="_blank" rel="noopener noreferrer">Албан заавар <ExternalLink size={13}/></a>}{compact&&<Link href={'/models/'+model.slug}>Бүрэн заавар <ArrowRight size={13}/></Link>}</div>
 </section>;
}

export function MediaSizeGuide(){return <section className="mediaSizeGuide"><div><span className="eyebrow">ХЭМЖЭЭГЭЭ ЗӨВ СОНГО</span><h2>Хаана нийтлэх вэ?</h2><p>Кадрын харьцаа нь хэлбэр, нягтаршил нь дүрсний хэмжээ. Загвар бүрийн зөвшөөрсөн сонголтоор үүсгэнэ.</p></div><div className="formatTiles">{[{ratio:'9:16',title:'Reels · TikTok · Shorts',text:'Босоо дэлгэц дүүрэн видео',w:36,h:64},{ratio:'16:9',title:'YouTube · Website',text:'Хэвтээ видео, танилцуулга',w:76,h:43},{ratio:'1:1',title:'Facebook · Instagram пост',text:'Дөрвөлжин нийтлэл',w:52,h:52},{ratio:'4:3',title:'Танилцуулга · Сонгодог кадр',text:'Бага зэрэг өргөн дүрслэл',w:64,h:48}].map(x=><article key={x.ratio}><div className="formatShapeStage"><span style={{width:x.w,height:x.h}}>{x.ratio}</span></div><b>{x.title}</b><p>{x.text}</p></article>)}</div><div className="resolutionNotes"><p><b>480p</b> — анхны туршилт</p><p><b>720p</b> — HD видео</p><p><b>1080p</b> — Full HD видео</p><p><b>1K / 2K / 4K</b> — зургийн хэмжээний түвшин</p></div><small>16:9 720p-ийн нийтлэг хэмжээ 1280×720, 1080p нь 1920×1080. Босоо болон бусад харьцаанд пикселийн хэмжээ өөр байна. 4K нь тусдаа түвшин; файлын MB хэмжээ нь хугацаа, шахалт, дуунаас хамаарна.</small></section>}
