"use client";
import { useEffect,useMemo,useState } from "react";import { useRouter,useSearchParams } from "next/navigation";import { models,getModel,estimateCredits } from "@/lib/models";import { Sidebar } from "@/components/sidebar";import { ArrowUp,ImagePlus,RefreshCw,Square,Upload,Video,WalletCards,X,CheckCircle2,LoaderCircle } from "lucide-react";
type User={id:string;email:string;name:string|null;role:string;credits:number};
type Gen={id:string;modelSlug:string;modelId:string;prompt:string;status:string;costCredits:number;output:any;error:any;createdAt:string;refunded:boolean};
function mediaFrom(output:any){if(!output)return null;if(typeof output?.video?.url==="string")return{type:"video",url:output.video.url};if(Array.isArray(output?.images)&&output.images[0]?.url)return{type:"image",url:output.images[0].url};if(typeof output?.url==="string")return{type:"video",url:output.url};return null}
export function StudioClient(){
 const router=useRouter(),params=useSearchParams();const group=params.get("group");
 const visible=useMemo(()=>group?models.filter(m=>m.group===group):models,[group]);
 const[selected,setSelected]=useState(visible[0]?.slug||models[0].slug),[prompt,setPrompt]=useState(""),[duration,setDuration]=useState(5),[resolution,setResolution]=useState("720p"),[aspect,setAspect]=useState("9:16"),[audio,setAudio]=useState(true),[imageUrl,setImageUrl]=useState(""),[videoUrl,setVideoUrl]=useState(""),[refs,setRefs]=useState<string[]>([]),[presetId,setPresetId]=useState(""),[presets,setPresets]=useState<any[]>([]),[user,setUser]=useState<User|null>(null),[history,setHistory]=useState<Gen[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const model=getModel(selected)!;const cost=estimateCredits(model,duration);
 useEffect(()=>{if(!visible.some(m=>m.slug===selected))setSelected(visible[0]?.slug||models[0].slug)},[group]);
 useEffect(()=>{setDuration(model.minDuration||5);setResolution(model.resolutions[0]);setAspect(model.aspectRatios[0]);setImageUrl("");setVideoUrl("");setRefs([]);setPresetId("");setPresets([]);if(model.slug==="genjutsu-restyle")fetch("/api/catalog/presets?kind=restyle").then(r=>r.ok?r.json():null).then(d=>setPresets(d?.items||[])).catch(()=>null)},[selected]);
 async function load(){const me=await fetch("/api/auth/me",{cache:"no-store"});const md=await me.json();if(!md.user){router.push("/login");return}setUser(md.user);const r=await fetch("/api/generations",{cache:"no-store"});if(r.ok){const d=await r.json();setHistory(d.generations||[]);setUser(u=>u?{...u,credits:d.user?.credits??u.credits}:u)}}
 useEffect(()=>{load()},[]);
 useEffect(()=>{const active=history.filter(g=>!["COMPLETED","FAILED","NSFW","CANCELED"].includes(g.status));if(!active.length)return;const timer=setInterval(async()=>{for(const g of active){const r=await fetch(`/api/generations/${g.id}`,{cache:"no-store"});if(r.ok){const d=await r.json();setHistory(old=>old.map(x=>x.id===g.id?d.generation:x));if(d.credits!==undefined)setUser(u=>u?{...u,credits:d.credits}:u)}}},4500);return()=>clearInterval(timer)},[history.map(g=>g.id+g.status).join("|")]);
 async function upload(file:File,kind:"image"|"video"|"ref"){setMessage("Файл байршуулж байна…");if(file.size>200*1024*1024){setMessage("Файл 200MB-аас бага байна.");return}const s=await fetch("/api/uploads/sign",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({contentType:file.type})});const data=await s.json();if(!s.ok)throw new Error(data.error||"Upload sign алдаа");const up=await fetch(data.upload_url,{method:"PUT",headers:data.upload_headers||{},body:file,credentials:"omit"});if(!up.ok)throw new Error("Файл upload амжилтгүй.");const url=data.public_url;if(kind==="image")setImageUrl(url);else if(kind==="video")setVideoUrl(url);else setRefs(v=>[...v,url].slice(0,16));setMessage("Файл бэлэн.") }
 async function submit(){if(!user)return;setBusy(true);setMessage("");try{const r=await fetch("/api/generations",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({modelSlug:selected,prompt,duration,resolution,aspectRatio:aspect,generateAudio:audio,imageUrl,videoUrl,referenceUrls:refs,presetId,enhancePrompt:true})});const d=await r.json();if(r.status===401){router.push("/login");return}if(!r.ok)throw new Error(d.error||"Generation алдаа");setHistory(h=>[d.generation,...h]);setUser(u=>u?{...u,credits:d.credits}:u);setMessage("Generation queue-д орлоо.")}catch(e){setMessage(e instanceof Error?e.message:"Алдаа гарлаа.")}finally{setBusy(false)}}
 async function cancel(id:string){await fetch(`/api/generations/${id}`,{method:"DELETE"});await load()}
 async function logout(){await fetch("/api/auth/logout",{method:"POST"});router.push("/login")}
 return <main className="shell"><Sidebar/><section className="content studioPage"><header className="topbar"><div><b>RAVS Studio</b><span>Higgsfield-powered creative workspace</span></div><div className="topActions"><a href="/billing" className="creditPill"><WalletCards size={15}/>{user?.credits??0} credit</a><button className="ghost" onClick={logout}>Гарах</button></div></header>
 <div className="studioLayout"><aside className="modelRail"><h3>Models</h3>{visible.map(m=><button key={m.slug} className={selected===m.slug?"modelPick active": "modelPick"} onClick={()=>setSelected(m.slug)}><span>{m.name}</span><small>{m.badge} · {m.creditRate}{m.pricingType==="second"?"/сек":""}</small></button>)}</aside>
 <section className="creationArea"><div className="workspaceTitle"><div><small>{model.group.toUpperCase()}</small><h1>{model.name}</h1><p>{model.description}</p></div><div className="priceTag">{cost} credit</div></div>
 <div className="proGenerator"><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="Монгол хэлээр хүссэн дүрслэл, камер, хөдөлгөөн, уур амьсгалаа бичээрэй…"/>
 <div className="uploadGrid">{model.supportsImage&&<label className={imageUrl?"uploadBox done":"uploadBox"}><ImagePlus size={18}/><span>{imageUrl?"Зураг бэлэн":"Эхлэл зураг"}</span><input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0],"image").catch(x=>setMessage(x.message))}/></label>}{model.supportsVideo&&<label className={videoUrl?"uploadBox done":"uploadBox"}><Video size={18}/><span>{videoUrl?"Видео бэлэн":"Source video"}</span><input type="file" accept="video/mp4,video/quicktime" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0],"video").catch(x=>setMessage(x.message))}/></label>}{model.supportsMultipleReferences&&<label className="uploadBox"><Upload size={18}/><span>Reference ({refs.length})</span><input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0],"ref").catch(x=>setMessage(x.message))}/></label>}</div>
 {presets.length>0&&<select className="fullSelect" value={presetId} onChange={e=>setPresetId(e.target.value)}><option value="">Style preset сонгох</option>{presets.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select>}
 <div className="settingsRow">{model.minDuration&&<label>Хугацаа<select value={duration} onChange={e=>setDuration(Number(e.target.value))}>{Array.from({length:(model.maxDuration!-model.minDuration!)+1},(_,i)=>model.minDuration!+i).map(x=><option key={x} value={x}>{x} сек</option>)}</select></label>}<label>Чанар<select value={resolution} onChange={e=>setResolution(e.target.value)}>{model.resolutions.map(x=><option key={x}>{x}</option>)}</select></label><label>Харьцаа<select value={aspect} onChange={e=>setAspect(e.target.value)}>{model.aspectRatios.map(x=><option key={x}>{x}</option>)}</select></label>{model.supportsAudio&&<label className="toggleLabel">Audio<input type="checkbox" checked={audio} onChange={e=>setAudio(e.target.checked)}/></label>}<button className="go" disabled={busy||!prompt.trim()} onClick={submit}>{busy?<LoaderCircle className="spin" size={18}/>:<ArrowUp size={18}/>} {busy?"Илгээж байна":"Үүсгэх"}</button></div>{message&&<div className="statusMsg">{message}</div>}</div>
 <div className="historyHead"><h2>Миний бүтээлүүд</h2><button className="ghost" onClick={load}><RefreshCw size={14}/> Шинэчлэх</button></div><div className="historyGrid">{history.map(g=>{const media=mediaFrom(g.output);return <article className="genCard" key={g.id}><div className="genPreview">{media?.type==="video"?<video src={media.url} controls preload="metadata"/>:media?.type==="image"?<img src={media.url} alt="AI output"/>:<div className="placeholderMedia">{["PENDING","SUBMITTED","PROCESSING"].includes(g.status)?<LoaderCircle className="spin"/>:<Square/>}</div>}<span className={"statusBadge "+g.status.toLowerCase()}>{g.status}</span></div><div className="genMeta"><b>{getModel(g.modelSlug)?.name||g.modelSlug}</b><p>{g.prompt||"Reference workflow"}</p><small>{g.costCredits} credit · {new Date(g.createdAt).toLocaleString("mn-MN")}</small>{!["COMPLETED","FAILED","NSFW","CANCELED"].includes(g.status)&&<button className="cancelBtn" onClick={()=>cancel(g.id)}><X size={13}/> Цуцлах</button>}{g.refunded&&<small className="refund"><CheckCircle2 size={12}/> Credit буцаасан</small>}</div></article>})}{!history.length&&<div className="emptyState">Энд таны AI бүтээлүүд гарна.</div>}</div>
 </section></div></section></main>
}
