import Link from "next/link";
import { ArrowRight, BookOpen, Check } from "lucide-react";
import { WorkflowIcon } from "@/components/workflow-icon";
import { DemoPlayer } from "@/components/demo-player";
const tutorials = [
 {id:"video",title:"Санаагаа видео болгох",hint:"Текст эсвэл зургаас эхэл",source:"https://higgsfield.ai/seedance-2-5-community",href:"/studio?model=seedance-2-5",steps:["Үйл явдал, орчин, камерын хөдөлгөөнөө тодорхой бич.","9:16 босоо эсвэл 16:9 өргөн харьцааг сонго.","Загварт боломжтой хугацаа, нягтралыг тохируулж үүсгэ.","Бүтээлүүд хэсгээс үр дүнгээ үзэж, татаж ав."],prompt:"Бороотой Улаанбаатарын гудамжаар алхаж буй залуу, нойтон замд неон гэрэл ойно. Камер араас нь зөөлөн дагана. Бодит кино зураглал."},
 {id:"genjutsu",title:"Хөдөлгөөнөө хадгалж дүрслэлийг солих",hint:"Genjutsu · видео хувиргалт",source:"https://higgsfield.ai/higgsfield-genjutsu-presets",src:"https://static-public-media.higgsfield.ai/cards/33cd35c5-e687-46cd-8fa5-2d097d4206dc.mp4",href:"/studio?group=Genjutsu",steps:["Өөрчлөх эх видеогоо оруул.","Хөдөлгөөн шилжүүлэх, объект солих эсвэл хэв маяг өөрчлөх хэрэгслээ сонго.","Шинэ дүр эсвэл бүтээгдэхүүний жишиг зургийг оруул.","Өөрчлөх хэсгийг тодорхой бичээд үр дүнг эхтэй нь харьцуул."],prompt:"Эх видеоны камер, хөдөлгөөн, хугацааг хадгал. Орчныг неон гэрэлтэй ирээдүйн хот болго."},
 {id:"marketing",title:"Бүтээгдэхүүний зар бэлтгэх",hint:"Маркетинг · бүтээгдэхүүний зураг",source:"https://higgsfield.ai/ads-studio",src:"https://static-public-media.higgsfield.ai/cards/6e0b1c30-6596-4f32-9452-c4b9f8890329.mp4",href:"/marketing",steps:["Бүтээгдэхүүний тод, сайн гэрэлтүүлэгтэй зураг оруул.","Хэнд зориулсан зар болох, орчин, өнгөө бич.","Пост, story эсвэл дэлгүүрийн зургийн харьцааг сонго.","Бүтээгдэхүүний хэлбэр, шошго, бичвэрийг шалгаад татаж ав."],prompt:"Бүтээгдэхүүний хэлбэр, шошгыг хадгал. Хар дэвсгэр, зөөлөн шар гэрэл, цэвэр сүүдэртэй premium сурталчилгааны зураг."},
 {id:"influencer",title:"Нэг төрхтэй AI дүр бүтээх",hint:"Дүр · хөрөг · хөдөлгөөн",source:"https://higgsfield.ai/ai-influencer-studio",src:"https://static-public-media.higgsfield.ai/cards/426e4ec0-3f06-4bef-a2ae-ac7a2de4a6c1.mp4",href:"/influencer",steps:["Дүрийн төрх, хувцас, орчныг тодорхойл.","Жишиг хөрөг эсвэл дүрийн reference оруул.","Хэд хэдэн өнцөг, байрлалаар зураг үүсгэ.","Төрхөө шалгаад хөдөлгөөн шилжүүлэх хэрэгслээр үргэлжлүүл."],prompt:"Ижил нүүрний төрхтэй Монгол дүр. Байгалийн арьс, студийн зөөлөн гэрэл, нэгэн ижил хувцас, олон өнцгийн хөрөг."},
 {id:"image",title:"Постер ба зураг бүтээх",hint:"Зураг · дизайн · хөрөг",source:"https://higgsfield.ai/ai/image",href:"/studio?surface=image&model=soul-2",steps:["Хөрөг, постер эсвэл бүтээгдэхүүний зураг гэдгээ сонго.","Гол объект, гэрэл, өнгө, хэв маягийг бич.","Шаардлагатай жишиг зураг болон харьцааг нэм.","Үүссэн зургийн нүүр, гар, бичвэрийг шалга."],prompt:"Монгол төрхтэй модель, минимал студийн орчин, зөөлөн цонхны гэрэл, бодит арьсны бүтэц, editorial хөрөг."},
 {id:"cinema",title:"Киноны хэсэг бүтээх",hint:"Өгүүлэмж · камер · гэрэл",source:"https://higgsfield.ai/cinematic-video-generator",href:"/cinema",steps:["Нэг хэсэгт болох үйл явдлыг товч тодорхойл.","Дүр, орчин, жанр, гэрэлтүүлгээ тогтоо.","Камерын нэг тодорхой хөдөлгөөн, кадрын харьцааг сонго.","Жишиг материал нэмээд дүрийн үргэлжлэл, хөдөлгөөнийг шалга."],prompt:"Нэг дүр харанхуй хонгилын төгсгөл дэх гэрэл рүү алхана. Камер зөөлөн ойртож, хажуугийн гэрэл нүүрийг нь тодруулна."},
 {id:"apps",title:"Эффектээр богино видео хийх",hint:"Хувиралт · шилжилт · тренд",source:"https://higgsfield.ai/effects",href:"/apps",steps:["Жишээ эффектийг тоглуулж хөдөлгөөнийг ажигла.","Гол объект тод харагдах эх зураг эсвэл видео оруул.","Хүссэн хувиралт, хөдөлгөөнийг нэг утгатай бич.","Үүссэн үр дүнг үзэж, шаардлагатай бол prompt-оо нарийвчил."],prompt:"Гол дүр жижиг гэрэлт хэсгүүд болон задарч, салхинд аажмаар тархана. Камер тогтвортой, киноны зөөлөн арын гэрэл."},
];
export function WorkflowTutorials({compact=false}:{compact?:boolean}) {
 return <section className="productSection tutorialSection"><div className="sectionTitleRow"><div><small>АЛХАМЧИЛСАН ЗААВАР</small><h2>Үзээд, дагаад, өөрөө бүтээ</h2><p>Хэрэгслээ ойлгож, Монгол жишиг prompt-оор шууд эхлээрэй.</p></div>{compact&&<Link href="/video-guide"><BookOpen size={15}/> Бүх заавар</Link>}</div>
 <div className="tutorialGrid">{(compact?tutorials.slice(0,4):tutorials).map(t=><article className="tutorialCard" id={t.id} key={t.id}>
 {t.src&&<DemoPlayer source={t.source} src={t.src} title={t.title}/>}
 <div className="tutorialBody"><span className="tutorialKicker"><WorkflowIcon id={t.id} size={18}/> {t.hint}</span><h3>{t.title}</h3><ol>{t.steps.map(step=><li key={step}><Check size={13}/><span>{step}</span></li>)}</ol>
 <details><summary>Монгол prompt жишээ</summary><p className="tutorialPrompt">{t.prompt}</p></details><div className="tutorialLinks"><Link className="primary" href={t.href+ (t.href.includes('?')?'&':'?')+'prompt='+encodeURIComponent(t.prompt)}>Туршиж бүтээх <ArrowRight size={13}/></Link><a href={t.source} target="_blank" rel="noopener noreferrer">Higgsfield жишээ ↗</a></div></div>
 </article>)}</div></section>;
}
